-- Drones
INSERT INTO drone (serial_number, model, weight_limit, battery_capacity, state, created_at, updated_at) VALUES
('DRN001', 'LIGHTWEIGHT', 100, 100, 'IDLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN002', 'MIDDLEWEIGHT', 200, 80, 'IDLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN003', 'CRUISERWEIGHT', 300, 60, 'IDLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN004', 'HEAVYWEIGHT', 500, 100, 'IDLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN005', 'LIGHTWEIGHT', 150, 20, 'IDLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN006', 'MIDDLEWEIGHT', 250, 90, 'LOADING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN007', 'CRUISERWEIGHT', 350, 70, 'LOADED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN008', 'HEAVYWEIGHT', 450, 50, 'DELIVERING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN009', 'LIGHTWEIGHT', 120, 10, 'RETURNING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DRN010', 'MIDDLEWEIGHT', 220, 100, 'IDLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Medications
INSERT INTO medication (name, weight, code, image_url, created_at, updated_at) VALUES
('Medication-A', 50, 'MED_A', 'http://example.com/med_a.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Medication-B', 100, 'MED_B', 'http://example.com/med_b.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Medication-C', 70, 'MED_C', 'http://example.com/med_c.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Medication-D', 20, 'MED_D', 'http://example.com/med_d.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Medication-E', 150, 'MED_E', 'http://example.com/med_e.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);